language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn test
notifications:
  slack: mt0re:RbmL8nBFkcg5OWtIvTCxnRB4
  email:
      recipients:
        - matiastorezani@gmail.com
        - mtorezani93@gmail.com
      on_success: always
      on_failure: always
deploy: 
  provider: heroku
  skip_cleanup: true
  keep_history: true
  api_key: 65403007-9db8-412e-adf5-2e63f9aa60f8
  app: platzistore-backend-mt0re
  on:
    repo: mt0re/platzi-store-backend